# Info about you
name: Yuko Nakagi
position: Graduate Student
email:
company_name: Osaka University
company_url: https://www.fbs.osaka-u.ac.jp/en/
place_name: Osaka, Japan

# Blog info
title: Yuko Nakagi
description: Personal website
url: https://yunagi-64.github.io
main_github_io: true
long_description: >-
    Hi, I am a first-year master's student at Osaka University.
    My research interest is to investigate how the human brain perceives and recognizes the world.
    Recently, I am particularly interested in exploring the correspondence between the human brain and artificial intelligence.

# Social links
github_url: https://github.com/yunagi-64
# linkedin_url:
social:
  links:
    # - http://www.linkedin.com/in/your-name
    - https://github.com/yunagi-64

# Images + files
logo: assets/img/my_image.JPG
cv_url: assets/files/cv.pdf
resume_url: assets/files/resume.pdf

# Blog settings
markdown: kramdown
plugins:
  - jekyll-seo-tag
highlighter: rouge
color_mode: light  # auto, light, or dark
comments: false
disqus_shortname: none
syntax_highlight_stylesheet: syntax_highlight.css

# Colors - light mode
colors:
  text: 282828
  tag: dbefdc
  tag_hover: 93cf95
  header_background: 2b422b
  header_text: dbefdc
  header_link_hover: 93cf95
  links: 459c48
  links_visited: 357a38

# Colors - dark mode
colors_dark:
  background: 333
  text: ccc
  tag: 2e6830
  tag_hover: 93cf95
  header_background: 232
  header_text: 93cf95
  header_link: 93cf95
  header_link_hover: 459c48
  links: 459c48
  links_visited: 357a38