# Info about you
name: Yuko Nakagi
position: Graduate Student
email:
company_name: Osaka University
company_url: https://www.fbs.osaka-u.ac.jp/en/
place_name: Osaka, Japan

# Blog info
title: Yuko Nakagi
description: Personal website
url: https://yunagi-64.github.io
main_github_io: true
long_description: >-
    Hi, I am a second-year master's student at Osaka University.
    My research interest is to investigate how the human brain perceives and recognizes the world.
    Recently, I have been particularly interested in exploring the relationship between the human brain and artificial intelligence, especially large language models (LLMs).

# Social links
github_url: https://github.com/yunagi-64
googlescholar_url: https://scholar.google.com/citations?user=JZLIe04AAAAJ&hl=ja&oi=sra
social:
  links:
    - https://github.com/yunagi-64 
    - https://scholar.google.com/citations?user=JZLIe04AAAAJ&hl=ja&oi=sra

# Images + files
logo: assets/img/my_image.JPG
cv_url: assets/files/cv.pdf
resume_url: assets/files/resume.pdf

# Blog settings
markdown: kramdown
plugins:
  - jekyll-seo-tag
highlighter: rouge
color_mode: light  # auto, light, or dark
comments: false
disqus_shortname: none
syntax_highlight_stylesheet: syntax_highlight.css

# Colors - light mode
colors:
  text: 282828
  tag: dbefdc
  tag_hover: 93cf95
  header_background: cfeffb
  header_text: 002e3e
  header_link_hover: 000f14
  links: 4171f7
  links_visited: 0c4cfe

# Colors - dark mode
colors_dark:
  background: 333333
  text: cccccc
  tag: 2e3568
  tag_hover: 93a9cf
  header_background: rgb(34, 45, 51)
  header_text: 93b2cf
  header_link: 93c3cf
  header_link_hover: 45869c
  links: 458c9c
  links_visited: 2f8699